### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by ylboerner** [gematik/ISiK-Dokumentenaustausch#156]
- [ ] SUSHI Version erhöhen
- [ ] Validierungsfehler prüfen
- [ ] Use slice name instead of numeric index access
- [ ] Fix eventual errors

Vergleiche ggf. mit Terminplanung : https://github.com/gematik/spec-ISiK-Terminplanung/pull/128

```[tasklist]
### Tasks
- [ ] PTDATA-672
```

**Comment by ylboerner** [comment]
Done, via #166
